openapi: "3.0.0"
info:
  version: 1.0.0
  title: AI Radio Website

paths:
  /:
    get:
      operationId: index
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-website'
        object: 'index.html'
  /{file+}:
    get:
      operationId: website
      parameters:
        - name: file
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-website'
        object: '{file}'
  /images/{file+}:
    get:
      operationId: posters
      parameters:
        - name: file
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-images'
        object: '{file}'
  /stream:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: "${container_id}"
        service_account_id: "${service_account_id}"
      parameters:
      - explode: false
        in: path
        name: proxy
        required: false
        schema:
          default: '-'
          type: string
        style: simple