openapi: "3.0.0"
info:
  version: 1.0.0
  title: AI Radio Website

paths:
  /:
    get:
      operationId: index
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-website'
        object: 'index.html'
  /ping:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          "text/plain": "pong"
  /{file+}:
    get:
      operationId: website
      parameters:
        - name: file
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-website'
        object: '{file}'
  /images/{file+}:
    get:
      operationId: posters
      parameters:
        - name: file
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: 'ai-radio-images'
        object: '{file}'
  /stream:
    get:
      x-yc-apigateway-integration:
        headers:
          '*': '*'
        method: get
        query:
          '*': '*'
        timeouts:
          read: 30.0
          connect: 5.0
        type: http
        url: http://${vm_ip}