{{- if .Values.ingress.enabled -}}
apiVersion: alb.yc.io/v1alpha1
kind: IngressGroupSettings
metadata:
  name: base-settings
  namespace: {{ .Values.namespace }}
logOptions:
  {{- with .Values.ingress.logGroupId }}
  logGroupID: {{ . }}
  {{- end }}
{{- end }}