{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "caster.serviceAccountName" . }}
  namespace: ai-radio
  labels:
    {{- include "caster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "caster.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "caster.serviceAccountName" . }}
  namespace: ai-radio
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "caster.serviceAccountName" . }}-token
  namespace: ai-radio
  annotations:
    kubernetes.io/service-account.name: {{ include "caster.serviceAccountName" . }}
{{- end }}