name: Terraform Yandex Cloud Integration

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.10.5"  # Specify the Terraform version
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}  # Yandex Cloud folder ID
  YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}  # Yandex Cloud service account key JSON
  TF_CLI_CONFIG_FILE: "terraform/config.tfrc"
  ACCESS_KEY: ${{ secrets.YC_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.YC_SECRET_KEY }}
  TF_VAR_dns_verification_key: ${{ secrets.DNS_VERIFICATION_KEY }}
  TF_VAR_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
  TF_VAR_ssh_key_pub: ${{ secrets.TF_VAR_ssh_key_pub }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure Yandex Cloud credentials
        run: |
          mkdir -p ~/.config/yandex
          echo '${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}' > ~/.config/yandex/key.json

      - name: Terraform Init
        run: terraform -chdir=terraform/ init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"

      - name: Terraform Plan
        run: terraform -chdir=terraform/ plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply on main branch
        run: terraform -chdir=terraform/ apply -auto-approve tfplan
